services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - env_local
    env_file:
      - .env.local
    restart: unless-stopped
    networks:
      - cloudflare-tunnel

secrets:
  env_local:
    file: .env.local

networks:
  cloudflare-tunnel:
    external: true
